typedef enum {
    EXPRESSION_NULL = 0,
    EXPRESSION_ASSIGNMENT,
    EXPRESSION_GET,
    EXPRESSION_LITERAL,
    EXPRESSION_PRINT,
    EXPRESSION_FRAME,
    EXPRESSION_SEQUENCE
} EExpressionID;